"""
etf_data.py — ETF flow ingestion, storage, cross-source validation, and
the derived calculations (streak, momentum, pressure score) behind the
Bitcoin ETF Flow indicator.

Architecture (adapted to this project's actual shape - flat JSON files
regenerated by scheduled scripts, no database/server runtime):

    SoSoValue API (primary)      XOOMAR API (validation, IBIT/BITB/ARKB only)
            |                                |
            v                                v
    fetch_etf_flows.py              fetch_xoomar_etf.py
            |                                |
            +---------------+----------------+
                            v
                 ingest_and_store() below
                            |
              normalize, validate (same-subset
              comparison only), merge into
              data/etf_flows.json (revises the
              last REVISION_WINDOW_DAYS days)
                            |
                            v
                compute_indicator() below
              (streak / momentum / pressure /
               freshness - all Decimal-based)
                            |
                            v
                 build_site.py rendering

Money is handled as Decimal throughout (constructed via str() from the
API's floats to avoid inheriting float imprecision), never float, per the
requirement not to do financial arithmetic in floating point.
"""
import json
import os
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation

from fetch_etf_flows import get_btc_summary_history, get_ticker_history, XOOMAR_COVERED_TICKERS
from fetch_xoomar_etf import get_btc_flows as get_xoomar_btc_flows

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ETF_DATA_FILE = os.path.join(ROOT, "data", "etf_flows.json")

# Re-validate this many of the most recent trading days on every run, since
# providers can revise recent figures after initial publication.
REVISION_WINDOW_DAYS = 10
# How many days of history to keep/use for the 90D window + streak calc.
HISTORY_DAYS = 95

# Validation tolerance tiers - absolute USD difference and/or relative
# difference between SoSoValue's IBIT+BITB+ARKB subset and XOOMAR's total
# for the same tickers/date. Configurable here in one place; changing
# these is a deliberate, documented edit, not a silent one.
VALIDATION_TOLERANCE = {
    "MATCH": {"abs_usd": Decimal("5000000"), "rel": Decimal("0.02")},
    "CLOSE": {"abs_usd": Decimal("15000000"), "rel": Decimal("0.05")},
}

# Momentum thresholds (7D avg vs 30D avg, scaled by |30D avg| so the rule
# works the same whether the 30D trend itself is net inflow or outflow).
# pct_change = (avg7 - avg30) / max(|avg30|, floor)
MOMENTUM_FLOOR = Decimal("1000000")  # avoids divide-by-near-zero on a quiet 30D stretch
MOMENTUM_THRESHOLDS = {
    "ACCELERATING": Decimal("0.50"),
    "STRENGTHENING": Decimal("0.15"),
}


def _dec(value):
    """float/int/str -> Decimal via str() first, so we never inherit a
    binary float's imprecision into a dollar figure."""
    if value is None:
        return None
    try:
        return Decimal(str(value))
    except InvalidOperation:
        return None


def load_store():
    """Public read-only accessor - used by build_site.py to render the
    indicator without importing a private helper."""
    try:
        with open(ETF_DATA_FILE) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {"observations": {}}


_load_store = load_store  # internal alias, kept short at call sites below


def _save_store(store):
    with open(ETF_DATA_FILE, "w") as f:
        json.dump(store, f, indent=2, default=str)


def _validate_subset(sosovalue_subset_total, xoomar_subset_total):
    """MATCH / CLOSE / DIVERGENCE / UNAVAILABLE for one date, comparing
    SoSoValue's IBIT+BITB+ARKB subset against XOOMAR's total for those
    same three tickers - never SoSoValue's full-universe total, since
    XOOMAR doesn't cover every BTC ETF."""
    if xoomar_subset_total is None:
        return "UNAVAILABLE", None, None
    abs_diff = abs(sosovalue_subset_total - xoomar_subset_total)
    denom = abs(sosovalue_subset_total) if sosovalue_subset_total != 0 else None
    rel_diff = (abs_diff / denom) if denom else (Decimal("0") if abs_diff == 0 else Decimal("1"))

    m = VALIDATION_TOLERANCE["MATCH"]
    c = VALIDATION_TOLERANCE["CLOSE"]
    if abs_diff <= m["abs_usd"] and rel_diff <= m["rel"]:
        status = "MATCH"
    elif abs_diff <= c["abs_usd"] or rel_diff <= c["rel"]:
        status = "CLOSE"
    else:
        status = "DIVERGENCE"
    return status, abs_diff, rel_diff


def _explain_validation(status, tickers, xoomar_by_ticker_date, date):
    """Names which specific fund(s) actually drove a CLOSE/DIVERGENCE flag,
    instead of leaving it as an opaque "the subset disagreed." Discovered
    need: on 2026-09-29, IBIT and BITB matched XOOMAR within ~0.3%, but
    XOOMAR's ARKB showed $0 (holdings frozen at the same value for 4
    straight days) while SoSoValue showed +$33.2M - ARK 21Shares' own
    holdings-disclosure file (which XOOMAR derives ARKB from) had lagged a
    day, and the flow appeared in XOOMAR's data a day later instead. A
    single MATCH/CLOSE/DIVERGENCE label gave no hint this was one fund's
    disclosure timing, not a real cross-source data problem."""
    base = "SoSoValue IBIT+BITB+ARKB subset vs XOOMAR's holdings-derived total for the same three funds."
    if status in (None, "MATCH", "UNAVAILABLE"):
        return base

    diffs = []
    for ticker in XOOMAR_COVERED_TICKERS:
        so_value = _dec(tickers.get(ticker))
        xoomar_value = xoomar_by_ticker_date.get(ticker, {}).get(date)
        if so_value is None or xoomar_value is None:
            continue
        diffs.append((ticker, abs(so_value - xoomar_value), so_value, xoomar_value))
    if not diffs:
        return base

    diffs.sort(key=lambda t: t[1], reverse=True)
    worst_ticker, worst_diff, so_val, xo_val = diffs[0]
    if worst_diff < Decimal("1000000"):
        return base  # no single ticker stands out enough to call out by name
    return (f"{base} Driven mainly by {worst_ticker}: SoSoValue "
            f"${so_val/1_000_000:+.1f}M vs XOOMAR ${xo_val/1_000_000:+.1f}M for that fund alone "
            f"(the other covered funds were within tolerance) - often a one-day lag in that "
            f"issuer's own holdings-disclosure file rather than a real data problem.")


def ingest_and_store():
    """Fetches both sources, validates the last REVISION_WINDOW_DAYS days
    against XOOMAR (same-subset only), merges into data/etf_flows.json
    (revising existing dates rather than duplicating them), and returns
    the updated store. Never raises on XOOMAR failure - that source is
    validation-only and its absence must never block publishing the
    primary SoSoValue reading."""
    now = datetime.now(timezone.utc)
    sosovalue_rows = get_btc_summary_history(limit=HISTORY_DAYS)

    # Per-ticker history, just for the recent revision/validation window -
    # no need to pull 95 days of three separate ticker histories.
    ticker_rows_by_ticker = {}
    for ticker in XOOMAR_COVERED_TICKERS:
        try:
            ticker_rows_by_ticker[ticker] = {
                r["date"]: _dec(r["net_inflow"]) for r in get_ticker_history(ticker, days_back=REVISION_WINDOW_DAYS)
            }
        except Exception:
            ticker_rows_by_ticker[ticker] = {}

    xoomar_rows = get_xoomar_btc_flows(days=REVISION_WINDOW_DAYS + 5)
    xoomar_by_date = {}
    xoomar_by_ticker_date = {}  # {ticker: {date: flow}} - kept alongside the summed
                                # total so a CLOSE/DIVERGENCE flag can name which
                                # specific fund actually disagrees, not just "the
                                # subset" as an opaque blob.
    for row in xoomar_rows:
        ticker = row.get("ticker")
        if ticker not in XOOMAR_COVERED_TICKERS:
            continue
        d = row["date"]
        flow = _dec(row.get("flowUsd")) or Decimal("0")
        xoomar_by_date.setdefault(d, Decimal("0"))
        xoomar_by_date[d] += flow
        xoomar_by_ticker_date.setdefault(ticker, {})[d] = flow

    store = _load_store()
    observations = store.setdefault("observations", {})

    for i, row in enumerate(sosovalue_rows):
        date = row["date"]
        total_flow = _dec(row["total_net_inflow"])
        is_in_revision_window = i < REVISION_WINDOW_DAYS

        record = observations.get(date, {})
        previous_total = _dec(record.get("total_net_flow_usd")) if record else None

        tickers = dict(record.get("tickers", {}))
        if is_in_revision_window:
            for ticker, by_date in ticker_rows_by_ticker.items():
                if date in by_date:
                    tickers[ticker] = str(by_date[date])

        validation_status = record.get("validation_status")
        validation_diff, validation_pct = None, None
        validation_notes = record.get("validation_notes") or (
            "SoSoValue IBIT+BITB+ARKB subset vs XOOMAR's holdings-derived total for the same three funds.")
        if is_in_revision_window:
            sosovalue_subset = sum((_dec(v) for v in tickers.values() if v is not None), Decimal("0"))
            xoomar_subset = xoomar_by_date.get(date)
            validation_status, validation_diff, validation_pct = _validate_subset(sosovalue_subset, xoomar_subset)
            validation_notes = _explain_validation(validation_status, tickers, xoomar_by_ticker_date, date)

        revised = previous_total is not None and total_flow is not None and previous_total != total_flow

        observations[date] = {
            "date": date,
            "source": "sosovalue",
            "total_net_flow_usd": str(total_flow) if total_flow is not None else None,
            "cum_net_inflow_usd": str(_dec(row.get("cum_net_inflow"))) if row.get("cum_net_inflow") is not None else None,
            "fetched_at": now.isoformat(),
            "source_updated_at": None,
            "data_status": "settled",
            "tickers": tickers,
            "validation_status": validation_status,
            "validation_difference_usd": str(validation_diff) if validation_diff is not None else record.get("validation_difference_usd"),
            "validation_difference_pct": str(validation_pct) if validation_pct is not None else record.get("validation_difference_pct"),
            "validation_notes": validation_notes,
            "previous_value": str(previous_total) if revised else record.get("previous_value"),
            "revised_at": now.isoformat() if revised else record.get("revised_at"),
        }

    # Keep only the trailing HISTORY_DAYS+buffer dates so this file doesn't
    # grow forever.
    if len(observations) > HISTORY_DAYS + 30:
        keep_dates = sorted(observations.keys(), reverse=True)[:HISTORY_DAYS + 30]
        store["observations"] = {d: observations[d] for d in keep_dates}

    _save_store(store)
    return store


def compute_indicator(store, as_of=None):
    """Everything the homepage/indicator page needs, computed from stored
    observations - streak, cumulative windows, averages, momentum,
    pressure score, and freshness. Returns None if there's no data at all
    yet (e.g. before the first successful ingest)."""
    as_of = as_of or datetime.now(timezone.utc)
    observations = store.get("observations", {})
    dated_rows = [
        (d, _dec(o["total_net_flow_usd"]))
        for d, o in observations.items()
        if o.get("total_net_flow_usd") is not None
    ]
    if not dated_rows:
        return None
    dated_rows.sort(key=lambda x: x[0], reverse=True)  # latest first

    latest_date, latest_flow = dated_rows[0]
    flows = [f for _, f in dated_rows]
    available_days = len(flows)

    def window_sum(n):
        return sum(flows[:n], Decimal("0"))

    def window_avg(n):
        subset = flows[:n]
        return (sum(subset, Decimal("0")) / len(subset)) if subset else Decimal("0")

    # SoSoValue's free tier only ever serves ~20 trading days (1 month) of
    # history per request, regardless of the documented `limit` max - we
    # persist our own history in data/etf_flows.json across runs, so 30D/
    # 90D genuinely deepen over the weeks after this first goes live, but
    # a window isn't reported as real until we actually have that many
    # stored trading days. A 20-day sum mislabeled "30D" would be a real
    # number wearing the wrong label.
    have_30d = available_days >= 30
    have_90d = available_days >= 90

    streak_count = 0
    streak_sign = None
    for _, f in dated_rows:
        sign = "inflow" if f > 0 else ("outflow" if f < 0 else None)
        if sign is None:
            break
        if streak_sign is None:
            streak_sign = sign
        if sign != streak_sign:
            break
        streak_count += 1

    avg7 = window_avg(7)
    avg30 = window_avg(min(30, available_days))
    if not have_30d:
        momentum = "INSUFFICIENT_DATA"
    else:
        scale = max(abs(avg30), MOMENTUM_FLOOR)
        pct_change = (avg7 - avg30) / scale
        if pct_change >= MOMENTUM_THRESHOLDS["ACCELERATING"]:
            momentum = "ACCELERATING"
        elif pct_change >= MOMENTUM_THRESHOLDS["STRENGTHENING"]:
            momentum = "STRENGTHENING"
        elif pct_change <= -MOMENTUM_THRESHOLDS["ACCELERATING"]:
            momentum = "DECELERATING"
        elif pct_change <= -MOMENTUM_THRESHOLDS["STRENGTHENING"]:
            momentum = "WEAKENING"
        else:
            momentum = "NEUTRAL"

    # Pressure score: percentile rank of today's flow, blended with the
    # percentile rank of the trailing 7-day cumulative, within all stored
    # history. Percentile rank is inherently bounded 0-100 and can't be
    # dominated by one extreme day the way a raw-magnitude score could -
    # weighted toward the 7D figure (0.6) specifically so a single huge
    # daily print matters less than sustained flow.
    def percentile_rank(value, population):
        if not population:
            return 50
        below = sum(1 for v in population if v < value)
        return round(100 * below / len(population))

    rolling_7d_sums = [sum(flows[i:i + 7], Decimal("0")) for i in range(len(flows) - 6)] if len(flows) >= 7 else flows
    daily_pctile = percentile_rank(latest_flow, flows)
    weekly_pctile = percentile_rank(window_sum(7), rolling_7d_sums)
    pressure_score = round(0.4 * daily_pctile + 0.6 * weekly_pctile)

    days_old = (as_of.date() - datetime.strptime(latest_date, "%Y-%m-%d").date()).days
    if days_old <= 3:
        freshness = "CURRENT"
    elif days_old <= 5:
        freshness = "DELAYED"
    else:
        freshness = "STALE"

    latest_obs = observations[latest_date]

    return {
        "latest_date": latest_date,
        "latest_flow_usd": latest_flow,
        "available_days": available_days,
        "flow_3d_usd": window_sum(min(3, available_days)),
        "flow_7d_usd": window_sum(min(7, available_days)),
        "flow_30d_usd": window_sum(30) if have_30d else None,
        "flow_90d_usd": window_sum(90) if have_90d else None,
        "avg_7d_usd": avg7,
        "avg_30d_usd": avg30 if have_30d else None,
        "avg_90d_usd": window_avg(90) if have_90d else None,
        "have_30d": have_30d,
        "have_90d": have_90d,
        "streak_count": streak_count,
        "streak_direction": streak_sign or "flat",
        "momentum": momentum,
        "pressure_score": max(0, min(100, pressure_score)),
        "freshness": freshness,
        "days_old": days_old,
        "validation_status": latest_obs.get("validation_status"),
        "validation_difference_usd": latest_obs.get("validation_difference_usd"),
        "validation_difference_pct": latest_obs.get("validation_difference_pct"),
        "validation_notes": latest_obs.get("validation_notes"),
        "history": dated_rows[:HISTORY_DAYS],
    }


if __name__ == "__main__":
    store = ingest_and_store()
    result = compute_indicator(store)
    if result:
        thirty_d = f"${result['flow_30d_usd']:,.1f}" if result["have_30d"] else f"building ({result['available_days']}d so far)"
        print(f"Latest ({result['latest_date']}): ${result['latest_flow_usd']:,.1f} "
              f"| 7D ${result['flow_7d_usd']:,.1f} | 30D {thirty_d} "
              f"| streak {result['streak_count']} {result['streak_direction']} "
              f"| momentum {result['momentum']} | pressure {result['pressure_score']} "
              f"| freshness {result['freshness']} | validation {result['validation_status']}")
    else:
        print("No ETF flow data available yet.")
